name: Muzu

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node  
      run: actions/setup-node@v2-beta
      with:
        node-version: 12 
       
    - name: Installing surge
      run: npm install --global surge

    -name: deploying using surge
    run: surge ./ muzammilproject.surge.sh --token ${{ secrets.SURGE_TOKEN }}
